[workspace]
authors = ["SebastianLunaValoroso <sebas.lunav@outlook.es>"]
channels = ["conda-forge"]
name = "Datathon-Schneider-Electric"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.5.*"
mypy = ">=1.18.2,<2"
scikit-learn = ">=1.7.2,<2"
pandas = ">=2.3.3,<3"
ipykernel = ">=7.1.0,<8"
pip = ">=25.3,<26"
shap = ">=0.48.0,<0.49"
matplotlib = ">=3.10.8,<4"
